# version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: huyvu
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_ultra_secret_key_123456"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://huyvu:password@postgres:5432/raw_data
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      PYTHONPATH: /opt/airflow
      DB_USER: ${DB_USER}
      PG_HOST: ${PG_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      AIRFLOW_HOME: ${AIRFLOW_HOME}
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_ultra_secret_key_123456"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "\
        airflow db init && \
        airflow users create --username admin --password admin_password --firstname FirstName --lastname LastName --email huyvuquoc.work@gmail.com --role Admin && \
        exec airflow webserver"
    restart: unless-stopped
    
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - airflow-webserver
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://huyvu:password@postgres:5432/raw_data
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      PYTHONPATH: /opt/airflow
      DB_USER: ${DB_USER}
      PG_HOST: ${PG_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      AIRFLOW_HOME: ${AIRFLOW_HOME}
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_ultra_secret_key_123456"
    volumes:
      - ./dags:/opt/airflow/dags
    command: airflow scheduler
    restart: unless-stopped
volumes:
  pgdata:
  
